// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfI1hIPsqYs6L5GCGOgq0HxjblCDgHyrQ',
    appId: '1:214936672480:web:93a55b175d4283c429d885',
    messagingSenderId: '214936672480',
    projectId: 'kongrepad1',
    authDomain: 'kongrepad1.firebaseapp.com',
    storageBucket: 'kongrepad1.firebasestorage.app',
    measurementId: 'G-5ZXQLYPG14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDpp5I_D0CcRNvZ_KAfu5yLc0QezOlDX4',
    appId: '1:214936672480:android:949966285171475c29d885',
    messagingSenderId: '214936672480',
    projectId: 'kongrepad1',
    storageBucket: 'kongrepad1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAdA7Uj49n_AR0UenWjrUnuoLWHIGFlEg',
    appId: '1:214936672480:ios:5ca430ebf3e5573a29d885',
    messagingSenderId: '214936672480',
    projectId: 'kongrepad1',
    storageBucket: 'kongrepad1.firebasestorage.app',
    iosBundleId: 'tr.com.pinet.kongrepad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAdA7Uj49n_AR0UenWjrUnuoLWHIGFlEg',
    appId: '1:214936672480:ios:5ca430ebf3e5573a29d885',
    messagingSenderId: '214936672480',
    projectId: 'kongrepad1',
    storageBucket: 'kongrepad1.firebasestorage.app',
    iosBundleId: 'tr.com.pinet.kongrepad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfI1hIPsqYs6L5GCGOgq0HxjblCDgHyrQ',
    appId: '1:214936672480:web:e99706022248b0d929d885',
    messagingSenderId: '214936672480',
    projectId: 'kongrepad1',
    authDomain: 'kongrepad1.firebaseapp.com',
    storageBucket: 'kongrepad1.firebasestorage.app',
    measurementId: 'G-V10PYBNVG7',
  );
}
